# Generated by Django 5.0.1 on 2024-01-22 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("roles_app", "0003_rolesmodel_user"),
    ]

    operations = [
        migrations.RemoveField(model_name="rolesmodel", name="user",),
    ]
